---
version: "3.9"
services:
 #Registry Server
 registry-server:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-registry-server-2019:${IMAGE_TAG}"
  build: 
   context: .
   dockerfile: Dockerfile
   args:
     JAR_FILE_NAME: registry-server/build/libs/registry-server-1.0.0.jar
     PORT: 9209
     HOSTS_FILE: ${HOSTS_FILE}
 
 #Gateway Server
 gateway-server:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-gateway-server-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: gateway-server/build/libs/gateway-server-1.0.0.jar
     PORT: 9208
     HOSTS_FILE: ${HOSTS_FILE}
     
 #Auth Service
 auth-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-auth-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: auth-service/build/libs/auth-service-1.0.0.jar
     PORT: 9201
     HOSTS_FILE: ${HOSTS_FILE}
     
 #Config Service
 config-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-config-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: config-service/build/libs/config-service-1.0.0.jar
     PORT: 8777
     HOSTS_FILE: ${HOSTS_FILE}
 
 #Datasync Service
 datasync-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-datasync-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: DatsyncServiceDockerfile
    args:
     JAR_FILE_NAME: datasync-service/build/libs/datasync-service-1.0.0.jar
     PORT: 8082
     HOSTS_FILE: ${HOSTS_FILE}
     
 #Engine Service
 engine-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-engine-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: engine-service/build/libs/engine-service-1.0.0.jar
     PORT: 9410
     HOSTS_FILE: ${HOSTS_FILE}     
  
 #File Service
 file-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-file-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: file-service/build/libs/file-service-1.0.0.jar
     PORT: 9250
     HOSTS_FILE: ${HOSTS_FILE}
  
 #Integration Service
 integration-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-integration-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: integration-service/build/libs/integration-service-1.0.0.jar
     PORT: 9229
     HOSTS_FILE: ${HOSTS_FILE}
          
 #Inventory Service
 inventory-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-inventory-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: inventory-service/build/libs/inventory-service-1.0.0.jar
     PORT: 8080
     HOSTS_FILE: ${HOSTS_FILE}
  
 #Location Service
 location-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-location-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: location-service/build/libs/location-service-1.0.0.jar
     PORT: 9211
     HOSTS_FILE: ${HOSTS_FILE}

 #Payment Service
 payment-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-payment-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: payment-service/build/libs/payment-service-1.0.0.jar
     PORT: 9230
     HOSTS_FILE: ${HOSTS_FILE}

 #Product Service
 product-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-product-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: product-service/build/libs/product-service-1.0.0.jar
     PORT: 9210
     HOSTS_FILE: ${HOSTS_FILE}
     
 #Report Service
 report-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-report-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: ReportServiceDockerfile
    args:
     JAR_FILE_NAME: report-service/build/libs/report-service-1.0.0.jar
     PORT: 9092
     HOSTS_FILE: ${HOSTS_FILE}
     
 #Sales Service
 sales-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-sales-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: sales-service/build/libs/sales-service-1.0.0.jar
     PORT: 8081
     HOSTS_FILE: ${HOSTS_FILE}
  
 #Store Service
 store-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-store-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: store-service/build/libs/store-service-1.0.0.jar
     PORT: 9306
     HOSTS_FILE: ${HOSTS_FILE}
     
 #User Service
 user-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-user-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: user-service/build/libs/user-service-1.0.0.jar
     PORT: 9204
     HOSTS_FILE: ${HOSTS_FILE}
     
 #Workflow Service
 workflow-service:
  image: "172.31.48.245:8123/${ENV_NAME}-nap-eposs-workflow-service-2019:${IMAGE_TAG}"
  build: 
    context: .
    dockerfile: Dockerfile
    args:
     JAR_FILE_NAME: workflow-service/build/libs/workflow-service-1.0.0.jar
     PORT: 8887
     HOSTS_FILE: ${HOSTS_FILE} 
   
...
